# Docker script for building NeMo container with GWE fault tolerance, using current source code

# How to build and push the image:
# 0. update code in repo, remember to pull submodules (git pull --recurse-submodules)
# 1. docker login gitlab-master.nvidia.com:5005
# 2. docker build -t 'gitlab-master.nvidia.com:5005/dl/gwe/fault_tolerance_related/nemo-gwe-ft:dummy_tag' -f Dockerfile_fault_tolerance .
# 3. docker push 'gitlab-master.nvidia.com:5005/dl/gwe/fault_tolerance_related/nemo-gwe-ft:dummy_tag'

FROM nvcr.io/nvidia/pytorch:23.10-py3

RUN apt-get update && apt-get install -y libsndfile1 ffmpeg

RUN rm -rf /opt/NeMo
COPY . /opt/NeMo
RUN cd /opt/NeMo && pip install -e ./fault_tolerance && ./reinstall.sh
